///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Sid_FCGAProject.Project_Repository
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Common_repo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("51ef24ff-d60d-4f02-8550-06169a5f31ae")]
    public partial class Common_repo : RepoGenBaseFolder
    {
        static Common_repo instance = new Common_repo();
        Common_repoFolders.RecordsViewAppFolder _recordsview;

        /// <summary>
        /// Gets the singleton class instance representing the Common_repo element repository.
        /// </summary>
        [RepositoryFolder("51ef24ff-d60d-4f02-8550-06169a5f31ae")]
        public static Common_repo Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Common_repo() 
            : base("Common_repo", "/", null, 0, false, "51ef24ff-d60d-4f02-8550-06169a5f31ae", ".\\RepositoryImages\\Common_repo51ef24ff.rximgres")
        {
            _recordsview = new Common_repoFolders.RecordsViewAppFolder(this);
        }

#region Variables

        string _QA_Agent_Env = "https://qawinston.fwcins.com/FWCPortal/User/Login/Login.html";

        /// <summary>
        /// Gets or sets the value of variable QA_Agent_Env.
        /// </summary>
        [TestVariable("0c1e36ea-c859-4769-8592-9645835e4c0c")]
        public string QA_Agent_Env
        {
            get { return _QA_Agent_Env; }
            set { _QA_Agent_Env = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("51ef24ff-d60d-4f02-8550-06169a5f31ae")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RecordsView folder.
        /// </summary>
        [RepositoryFolder("bdb6190a-a9fa-4dd7-8f97-29827e934463")]
        public virtual Common_repoFolders.RecordsViewAppFolder RecordsView
        {
            get { return _recordsview; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Common_repoFolders
    {
        /// <summary>
        /// The RecordsViewAppFolder folder.
        /// </summary>
        [RepositoryFolder("bdb6190a-a9fa-4dd7-8f97-29827e934463")]
        public partial class RecordsViewAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _chrome_closedInfo;

            /// <summary>
            /// Creates a new RecordsView  folder.
            /// </summary>
            public RecordsViewAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RecordsView", "/dom[@domain='qawinston.fwcins.com']", parentFolder, 30000, null, false, "bdb6190a-a9fa-4dd7-8f97-29827e934463", "")
            {
                _chrome_closedInfo = new RepoItemInfo(this, "Chrome_Closed", "body", 30000, null, "7242ee16-205e-462b-9330-5e90c0d96fb0");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("bdb6190a-a9fa-4dd7-8f97-29827e934463")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bdb6190a-a9fa-4dd7-8f97-29827e934463")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Chrome_Closed item.
            /// </summary>
            [RepositoryItem("7242ee16-205e-462b-9330-5e90c0d96fb0")]
            public virtual Ranorex.BodyTag Chrome_Closed
            {
                get
                {
                    return _chrome_closedInfo.CreateAdapter<Ranorex.BodyTag>(true);
                }
            }

            /// <summary>
            /// The Chrome_Closed item info.
            /// </summary>
            [RepositoryItemInfo("7242ee16-205e-462b-9330-5e90c0d96fb0")]
            public virtual RepoItemInfo Chrome_ClosedInfo
            {
                get
                {
                    return _chrome_closedInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
