///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sid_FCGAProject.GL_Product
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CG2028FormDetails recording.
    /// </summary>
    [TestModule("5498d6f0-e5d7-4b92-8096-5b07d9ddd30b", ModuleType.Recording, 1)]
    public partial class CG2028FormDetails : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repository.
        /// </summary>
        public static global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repo = global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository.Instance;

        static CG2028FormDetails instance = new CG2028FormDetails();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CG2028FormDetails()
        {
            CG2028_CompanyName = "CG2028";
            CG2028_Address1 = "Address1";
            CG2028_Address2 = "Address2";
            CG2028_City = "Tampa";
            CG2028_ZipCode = "33604";
            CG2028No = "1";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CG2028FormDetails Instance
        {
            get { return instance; }
        }

#region Variables

        string _CG2028_CompanyName;

        /// <summary>
        /// Gets or sets the value of variable CG2028_CompanyName.
        /// </summary>
        [TestVariable("6677fd8f-6086-4d0b-ac62-f5fa4dbc23b0")]
        public string CG2028_CompanyName
        {
            get { return _CG2028_CompanyName; }
            set { _CG2028_CompanyName = value; }
        }

        string _CG2028_Address1;

        /// <summary>
        /// Gets or sets the value of variable CG2028_Address1.
        /// </summary>
        [TestVariable("697f0f44-c636-4ddb-88ee-ac074e67f394")]
        public string CG2028_Address1
        {
            get { return _CG2028_Address1; }
            set { _CG2028_Address1 = value; }
        }

        string _CG2028_Address2;

        /// <summary>
        /// Gets or sets the value of variable CG2028_Address2.
        /// </summary>
        [TestVariable("2f59980f-e7db-4a93-8bf6-2cb4c4b9e8af")]
        public string CG2028_Address2
        {
            get { return _CG2028_Address2; }
            set { _CG2028_Address2 = value; }
        }

        string _CG2028_City;

        /// <summary>
        /// Gets or sets the value of variable CG2028_City.
        /// </summary>
        [TestVariable("ca42c68f-78d2-4f18-8f74-97615d975112")]
        public string CG2028_City
        {
            get { return _CG2028_City; }
            set { _CG2028_City = value; }
        }

        string _CG2028_ZipCode;

        /// <summary>
        /// Gets or sets the value of variable CG2028_ZipCode.
        /// </summary>
        [TestVariable("555bf3fe-a3d7-4133-8065-b0aa73ddfb5d")]
        public string CG2028_ZipCode
        {
            get { return _CG2028_ZipCode; }
            set { _CG2028_ZipCode = value; }
        }

        string _CG2028No;

        /// <summary>
        /// Gets or sets the value of variable CG2028No.
        /// </summary>
        [TestVariable("f527539e-17ba-406f-9bf4-8ca17d1c964d")]
        public string CG2028No
        {
            get { return _CG2028No; }
            set { _CG2028No = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // Header text
            // Header text
            // Header text
            MergedUserCodeMethod(repo.ApplicationUnderTest.TxtCompanyNameCG2028Info, repo.ApplicationUnderTest.TxtAddress1CG2028Info, repo.ApplicationUnderTest.TxtAddress2CG2028Info, repo.ApplicationUnderTest.TxtCityCG2028Info, repo.ApplicationUnderTest.TxtZipCodeCG2028Info, repo.ApplicationUnderTest.TxtCompanyNameCG20281Info, repo.ApplicationUnderTest.TxtAddress1CG20281Info, repo.ApplicationUnderTest.TxtAddress2CG20281Info, repo.ApplicationUnderTest.TxtCityCG20281Info, repo.ApplicationUnderTest.TxtZipCodeCG20281Info, repo.ApplicationUnderTest.TxtCompanyNameCG20282Info, repo.ApplicationUnderTest.TxtAddress1CG20282Info, repo.ApplicationUnderTest.TxtAddress2CG20282Info, repo.ApplicationUnderTest.TxtCityCG20282Info, repo.ApplicationUnderTest.TxtZipCodeCG20282Info, CG2028No);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
