///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sid_FCGAProject.GL_Product
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CG2024FormDetails recording.
    /// </summary>
    [TestModule("36a2bdce-7834-4ca7-9c33-dcfe8a8e02a2", ModuleType.Recording, 1)]
    public partial class CG2024FormDetails : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repository.
        /// </summary>
        public static global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repo = global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository.Instance;

        static CG2024FormDetails instance = new CG2024FormDetails();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CG2024FormDetails()
        {
            CG2024_CompanyName = "CG2024";
            CG2024_Address1 = "Address1";
            CG2024_Address2 = "Address2";
            CG2024_City = "Tampa";
            CG2024_ZipCode = "33604";
            CG2024No = "2";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CG2024FormDetails Instance
        {
            get { return instance; }
        }

#region Variables

        string _CG2024_CompanyName;

        /// <summary>
        /// Gets or sets the value of variable CG2024_CompanyName.
        /// </summary>
        [TestVariable("ab134858-f3ac-4599-b774-32aa7adcb406")]
        public string CG2024_CompanyName
        {
            get { return _CG2024_CompanyName; }
            set { _CG2024_CompanyName = value; }
        }

        string _CG2024_Address1;

        /// <summary>
        /// Gets or sets the value of variable CG2024_Address1.
        /// </summary>
        [TestVariable("86d7a9dc-517a-4ca3-80c2-e8d5dd9894fb")]
        public string CG2024_Address1
        {
            get { return _CG2024_Address1; }
            set { _CG2024_Address1 = value; }
        }

        string _CG2024_Address2;

        /// <summary>
        /// Gets or sets the value of variable CG2024_Address2.
        /// </summary>
        [TestVariable("922a68e5-347b-4ea6-b65e-f656f0c33c70")]
        public string CG2024_Address2
        {
            get { return _CG2024_Address2; }
            set { _CG2024_Address2 = value; }
        }

        string _CG2024_City;

        /// <summary>
        /// Gets or sets the value of variable CG2024_City.
        /// </summary>
        [TestVariable("5b2be259-7c0f-481e-866a-3f207787b647")]
        public string CG2024_City
        {
            get { return _CG2024_City; }
            set { _CG2024_City = value; }
        }

        string _CG2024_ZipCode;

        /// <summary>
        /// Gets or sets the value of variable CG2024_ZipCode.
        /// </summary>
        [TestVariable("43a48fc2-5285-43ca-ac6a-b7b18295b99c")]
        public string CG2024_ZipCode
        {
            get { return _CG2024_ZipCode; }
            set { _CG2024_ZipCode = value; }
        }

        string _CG2024No;

        /// <summary>
        /// Gets or sets the value of variable CG2024No.
        /// </summary>
        [TestVariable("0d793dbf-789a-4930-aba3-ac1fa63a9fbe")]
        public string CG2024No
        {
            get { return _CG2024No; }
            set { _CG2024No = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // Header text
            // Header text
            MergedUserCodeMethod(repo.ApplicationUnderTest.TxtCompanyNameCG2024Info, repo.ApplicationUnderTest.TxtAddress1CG2024Info, repo.ApplicationUnderTest.TxtAddress2CG2024Info, repo.ApplicationUnderTest.TxtCityCG2024Info, repo.ApplicationUnderTest.TxtZipCodeCG2024Info, repo.ApplicationUnderTest.TxtCompanyNameCG20241Info, repo.ApplicationUnderTest.TxtAddress1CG20241Info, repo.ApplicationUnderTest.TxtAddress2CG20241Info, repo.ApplicationUnderTest.TxtCityCG20241Info, repo.ApplicationUnderTest.TxtZipCodeCG20241Info, repo.ApplicationUnderTest.TxtCompanyNameCG20242Info, repo.ApplicationUnderTest.TxtAddress1CG20242Info, repo.ApplicationUnderTest.TxtAddress2CG20242Info, repo.ApplicationUnderTest.TxtCityCG20242Info, repo.ApplicationUnderTest.TxtZipCodeCG20242Info, CG2024No);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
