///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sid_FCGAProject.GL_Product
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CG2005FormDetails recording.
    /// </summary>
    [TestModule("39e89db5-22e4-4f86-ad92-898a5dcb79b3", ModuleType.Recording, 1)]
    public partial class CG2005FormDetails : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repository.
        /// </summary>
        public static global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repo = global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository.Instance;

        static CG2005FormDetails instance = new CG2005FormDetails();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CG2005FormDetails()
        {
            CG2005_CompanyName = "CG2005";
            CG2005_Address1 = "Address1";
            CG2005_Address2 = "Address2";
            CG2005_City = "tampa";
            CG2005_ZipCode = "33604";
            CG2005No = "1";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CG2005FormDetails Instance
        {
            get { return instance; }
        }

#region Variables

        string _CG2005_CompanyName;

        /// <summary>
        /// Gets or sets the value of variable CG2005_CompanyName.
        /// </summary>
        [TestVariable("bd3b2ee8-039b-4fd2-a5b8-ac2858ee1237")]
        public string CG2005_CompanyName
        {
            get { return _CG2005_CompanyName; }
            set { _CG2005_CompanyName = value; }
        }

        string _CG2005_Address1;

        /// <summary>
        /// Gets or sets the value of variable CG2005_Address1.
        /// </summary>
        [TestVariable("66cfed14-74c7-40a3-aed3-87ed07f73e4d")]
        public string CG2005_Address1
        {
            get { return _CG2005_Address1; }
            set { _CG2005_Address1 = value; }
        }

        string _CG2005_Address2;

        /// <summary>
        /// Gets or sets the value of variable CG2005_Address2.
        /// </summary>
        [TestVariable("f0f12361-94f9-4bb6-be7d-f24e0b223139")]
        public string CG2005_Address2
        {
            get { return _CG2005_Address2; }
            set { _CG2005_Address2 = value; }
        }

        string _CG2005_City;

        /// <summary>
        /// Gets or sets the value of variable CG2005_City.
        /// </summary>
        [TestVariable("e0d3e8d6-2256-4f15-962a-470a9c13972d")]
        public string CG2005_City
        {
            get { return _CG2005_City; }
            set { _CG2005_City = value; }
        }

        string _CG2005_ZipCode;

        /// <summary>
        /// Gets or sets the value of variable CG2005_ZipCode.
        /// </summary>
        [TestVariable("efa40a13-630c-49c4-bdea-13a20836a2c4")]
        public string CG2005_ZipCode
        {
            get { return _CG2005_ZipCode; }
            set { _CG2005_ZipCode = value; }
        }

        string _CG2005No;

        /// <summary>
        /// Gets or sets the value of variable CG2005No.
        /// </summary>
        [TestVariable("012f85ce-4737-4c04-b42e-0f9ea0589e29")]
        public string CG2005No
        {
            get { return _CG2005No; }
            set { _CG2005No = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TxtCompanyNameCG2005' at Center.", repo.ApplicationUnderTest.TxtCompanyNameCG2005Info, new RecordItemIndex(0));
            repo.ApplicationUnderTest.TxtCompanyNameCG2005.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CG2005_CompanyName' with focus on 'ApplicationUnderTest.TxtCompanyNameCG2005'.", repo.ApplicationUnderTest.TxtCompanyNameCG2005Info, new RecordItemIndex(1));
            repo.ApplicationUnderTest.TxtCompanyNameCG2005.PressKeys(CG2005_CompanyName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TxtAddress1CG2005' at Center.", repo.ApplicationUnderTest.TxtAddress1CG2005Info, new RecordItemIndex(2));
            repo.ApplicationUnderTest.TxtAddress1CG2005.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CG2005_Address1' with focus on 'ApplicationUnderTest.TxtAddress1CG2005'.", repo.ApplicationUnderTest.TxtAddress1CG2005Info, new RecordItemIndex(3));
            repo.ApplicationUnderTest.TxtAddress1CG2005.PressKeys(CG2005_Address1);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TxtAddress2CG2005' at Center.", repo.ApplicationUnderTest.TxtAddress2CG2005Info, new RecordItemIndex(4));
            repo.ApplicationUnderTest.TxtAddress2CG2005.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CG2005_Address2' with focus on 'ApplicationUnderTest.TxtAddress2CG2005'.", repo.ApplicationUnderTest.TxtAddress2CG2005Info, new RecordItemIndex(5));
            repo.ApplicationUnderTest.TxtAddress2CG2005.PressKeys(CG2005_Address2);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TxtCityCG2005' at Center.", repo.ApplicationUnderTest.TxtCityCG2005Info, new RecordItemIndex(6));
            repo.ApplicationUnderTest.TxtCityCG2005.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CG2005_City' with focus on 'ApplicationUnderTest.TxtCityCG2005'.", repo.ApplicationUnderTest.TxtCityCG2005Info, new RecordItemIndex(7));
            repo.ApplicationUnderTest.TxtCityCG2005.EnsureVisible();
            Keyboard.Press(CG2005_City);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TxtZipCodeCG2005' at Center.", repo.ApplicationUnderTest.TxtZipCodeCG2005Info, new RecordItemIndex(8));
            repo.ApplicationUnderTest.TxtZipCodeCG2005.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CG2005_ZipCode' with focus on 'ApplicationUnderTest.TxtZipCodeCG2005'.", repo.ApplicationUnderTest.TxtZipCodeCG2005Info, new RecordItemIndex(9));
            repo.ApplicationUnderTest.TxtZipCodeCG2005.PressKeys(CG2005_ZipCode);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
