///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Sid_FCGAProject.GL_Product
{
    public partial class CG2024FormDetails
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void MergedUserCodeMethod(RepoItemInfo inputtagInfo, RepoItemInfo inputtagInfo1, RepoItemInfo inputtagInfo2, RepoItemInfo inputtagInfo3, RepoItemInfo inputtagInfo4, RepoItemInfo inputtagInfo5, RepoItemInfo inputtagInfo6, RepoItemInfo inputtagInfo7, RepoItemInfo inputtagInfo8, RepoItemInfo inputtagInfo9, RepoItemInfo inputtagInfo10, RepoItemInfo inputtagInfo11, RepoItemInfo inputtagInfo12, RepoItemInfo inputtagInfo13, RepoItemInfo inputtagInfo14, string CG2024No)
        {
        	
        	int CG2024N = Convert.ToInt32(CG2024No);
        	if(CG2024N == 1)
        	{
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'inputtagInfo' at Center.", inputtagInfo);
            inputtagInfo.FindAdapter<InputTag>().Click();
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CG2024_CompanyName' with focus on 'inputtagInfo'.", inputtagInfo);
            inputtagInfo.FindAdapter<InputTag>().PressKeys(CG2024_CompanyName);
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'inputtagInfo1' at Center.", inputtagInfo1);
            inputtagInfo1.FindAdapter<InputTag>().Click();
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CG2024_Address1' with focus on 'inputtagInfo1'.", inputtagInfo1);
            inputtagInfo1.FindAdapter<InputTag>().PressKeys(CG2024_Address1);
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'inputtagInfo2' at Center.", inputtagInfo2);
            inputtagInfo2.FindAdapter<InputTag>().Click();
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CG2024_Address2' with focus on 'inputtagInfo2'.", inputtagInfo2);
            inputtagInfo2.FindAdapter<InputTag>().PressKeys(CG2024_Address2);
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'inputtagInfo3' at Center.", inputtagInfo3);
            inputtagInfo3.FindAdapter<InputTag>().Click();
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CG2024_City' with focus on 'inputtagInfo3'.", inputtagInfo3);
            inputtagInfo3.FindAdapter<InputTag>().EnsureVisible();
            Keyboard.Press(CG2024_City);
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'inputtagInfo4' at Center.", inputtagInfo4);
            inputtagInfo4.FindAdapter<InputTag>().Click();
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CG2024_ZipCode' with focus on 'inputtagInfo4'.", inputtagInfo4);
            inputtagInfo4.FindAdapter<InputTag>().EnsureVisible();
            Keyboard.Press(CG2024_ZipCode);
            Report.Log(ReportLevel.Info, "Section", "Header text");
            
             }
        	
        	if(CG2024N > 1 && CG2024N < 3)
            {
            	
            	String[] CG2024_CN = CG2024_CompanyName.Split(',');
            	String[] CG2024_Add1 = CG2024_Address1.Split(',');
            	String[] CG2024_Add2 = CG2024_Address2.Split(',');
            	String[] CG2024_CI = CG2024_City.Split(',');
            	String[] CG2024_Zip = CG2024_ZipCode.Split(',');
        		
            for (int i=0;i<CG2024N;i++)
            {
            	
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'inputtagInfo5' at Center.", inputtagInfo5);
            inputtagInfo5.FindAdapter<InputTag>().Click();
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CG2024_CompanyName' with focus on 'inputtagInfo5'.", inputtagInfo5);
            inputtagInfo5.FindAdapter<InputTag>().PressKeys(CG2024_CN[0]);
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'inputtagInfo6' at Center.", inputtagInfo6);
            inputtagInfo6.FindAdapter<InputTag>().Click();
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CG2024_Address1' with focus on 'inputtagInfo6'.", inputtagInfo6);
            inputtagInfo6.FindAdapter<InputTag>().PressKeys(CG2024_Add1[0]);
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'inputtagInfo7' at Center.", inputtagInfo7);
            inputtagInfo7.FindAdapter<InputTag>().Click();
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CG2024_Address2' with focus on 'inputtagInfo7'.", inputtagInfo7);
            inputtagInfo7.FindAdapter<InputTag>().PressKeys(CG2024_Add2[0]);
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'inputtagInfo8' at Center.", inputtagInfo8);
            inputtagInfo8.FindAdapter<InputTag>().Click();
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CG2024_City' with focus on 'inputtagInfo8'.", inputtagInfo8);
            inputtagInfo8.FindAdapter<InputTag>().EnsureVisible();
            Keyboard.Press(CG2024_CI[0]);
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'inputtagInfo9' at Center.", inputtagInfo9);
            inputtagInfo9.FindAdapter<InputTag>().Click();
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CG2024_ZipCode' with focus on 'inputtagInfo9'.", inputtagInfo9);
            inputtagInfo9.FindAdapter<InputTag>().EnsureVisible();
            Keyboard.Press(CG2024_Zip[0]);
            Report.Log(ReportLevel.Info, "Section", "Header text");
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'inputtagInfo10' at Center.", inputtagInfo10);
            inputtagInfo10.FindAdapter<InputTag>().Click();
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CG2024_CompanyName' with focus on 'inputtagInfo10'.", inputtagInfo10);
            inputtagInfo10.FindAdapter<InputTag>().PressKeys(CG2024_CN[1]);
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'inputtagInfo11' at Center.", inputtagInfo11);
            inputtagInfo11.FindAdapter<InputTag>().Click();
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CG2024_Address1' with focus on 'inputtagInfo11'.", inputtagInfo11);
            inputtagInfo11.FindAdapter<InputTag>().PressKeys(CG2024_Add1[1]);
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'inputtagInfo12' at Center.", inputtagInfo12);
            inputtagInfo12.FindAdapter<InputTag>().Click();
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CG2024_Address2' with focus on 'inputtagInfo12'.", inputtagInfo12);
            inputtagInfo12.FindAdapter<InputTag>().PressKeys(CG2024_Add2[1]);
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'inputtagInfo13' at Center.", inputtagInfo13);
            inputtagInfo13.FindAdapter<InputTag>().Click();
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CG2024_City' with focus on 'inputtagInfo13'.", inputtagInfo13);
            inputtagInfo13.FindAdapter<InputTag>().EnsureVisible();
            Keyboard.Press(CG2024_CI[1]);
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'inputtagInfo14' at Center.", inputtagInfo14);
            inputtagInfo14.FindAdapter<InputTag>().Click();
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CG2024_ZipCode' with focus on 'inputtagInfo14'.", inputtagInfo14);
            inputtagInfo14.FindAdapter<InputTag>().EnsureVisible();
            Keyboard.Press(CG2024_Zip[1]);
            }
         }
        }
    }
}
