///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sid_FCGAProject.GL_Product
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CG2011FormDetails recording.
    /// </summary>
    [TestModule("db6f0bbc-93c1-455a-aad3-f6f75541bedf", ModuleType.Recording, 1)]
    public partial class CG2011FormDetails : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repository.
        /// </summary>
        public static global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repo = global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository.Instance;

        static CG2011FormDetails instance = new CG2011FormDetails();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CG2011FormDetails()
        {
            CG2011_CompanyName = "CG2011";
            CG2011_Address1 = "Address1";
            CG2011_Address2 = "Address2";
            CG2011_City = "Tampa";
            CG2011_ZipCode = "33604";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CG2011FormDetails Instance
        {
            get { return instance; }
        }

#region Variables

        string _CG2011_CompanyName;

        /// <summary>
        /// Gets or sets the value of variable CG2011_CompanyName.
        /// </summary>
        [TestVariable("a1d5e6df-2c4c-4218-b112-bb6359096604")]
        public string CG2011_CompanyName
        {
            get { return _CG2011_CompanyName; }
            set { _CG2011_CompanyName = value; }
        }

        string _CG2011_Address1;

        /// <summary>
        /// Gets or sets the value of variable CG2011_Address1.
        /// </summary>
        [TestVariable("e62306cc-e750-46be-9577-e2dea489bf9b")]
        public string CG2011_Address1
        {
            get { return _CG2011_Address1; }
            set { _CG2011_Address1 = value; }
        }

        string _CG2011_Address2;

        /// <summary>
        /// Gets or sets the value of variable CG2011_Address2.
        /// </summary>
        [TestVariable("4657eae2-a912-4a89-800b-357e3ad16d7f")]
        public string CG2011_Address2
        {
            get { return _CG2011_Address2; }
            set { _CG2011_Address2 = value; }
        }

        string _CG2011_City;

        /// <summary>
        /// Gets or sets the value of variable CG2011_City.
        /// </summary>
        [TestVariable("af4f641c-b863-4c42-b90d-51e640ef53b1")]
        public string CG2011_City
        {
            get { return _CG2011_City; }
            set { _CG2011_City = value; }
        }

        string _CG2011_ZipCode;

        /// <summary>
        /// Gets or sets the value of variable CG2011_ZipCode.
        /// </summary>
        [TestVariable("051bbd1b-cc90-42df-9d4f-85d5b773f257")]
        public string CG2011_ZipCode
        {
            get { return _CG2011_ZipCode; }
            set { _CG2011_ZipCode = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.MainContentHolder.TxtCompanyNameCG2011' at Center.", repo.ApplicationUnderTest.MainContentHolder.TxtCompanyNameCG2011Info, new RecordItemIndex(0));
            repo.ApplicationUnderTest.MainContentHolder.TxtCompanyNameCG2011.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CG2011_CompanyName' with focus on 'ApplicationUnderTest.MainContentHolder.TxtCompanyNameCG2011'.", repo.ApplicationUnderTest.MainContentHolder.TxtCompanyNameCG2011Info, new RecordItemIndex(1));
            repo.ApplicationUnderTest.MainContentHolder.TxtCompanyNameCG2011.PressKeys(CG2011_CompanyName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.MainContentHolder.TxtAddress1CG2011' at Center.", repo.ApplicationUnderTest.MainContentHolder.TxtAddress1CG2011Info, new RecordItemIndex(2));
            repo.ApplicationUnderTest.MainContentHolder.TxtAddress1CG2011.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CG2011_Address1' with focus on 'ApplicationUnderTest.MainContentHolder.TxtAddress1CG2011'.", repo.ApplicationUnderTest.MainContentHolder.TxtAddress1CG2011Info, new RecordItemIndex(3));
            repo.ApplicationUnderTest.MainContentHolder.TxtAddress1CG2011.PressKeys(CG2011_Address1);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.MainContentHolder.TxtAddress2CG2011' at Center.", repo.ApplicationUnderTest.MainContentHolder.TxtAddress2CG2011Info, new RecordItemIndex(4));
            repo.ApplicationUnderTest.MainContentHolder.TxtAddress2CG2011.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CG2011_Address2' with focus on 'ApplicationUnderTest.MainContentHolder.TxtAddress2CG2011'.", repo.ApplicationUnderTest.MainContentHolder.TxtAddress2CG2011Info, new RecordItemIndex(5));
            repo.ApplicationUnderTest.MainContentHolder.TxtAddress2CG2011.EnsureVisible();
            Keyboard.Press(CG2011_Address2);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.MainContentHolder.TxtCityCG20111' at Center.", repo.ApplicationUnderTest.MainContentHolder.TxtCityCG20111Info, new RecordItemIndex(6));
            repo.ApplicationUnderTest.MainContentHolder.TxtCityCG20111.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CG2011_City' with focus on 'ApplicationUnderTest.MainContentHolder.TxtCityCG20111'.", repo.ApplicationUnderTest.MainContentHolder.TxtCityCG20111Info, new RecordItemIndex(7));
            repo.ApplicationUnderTest.MainContentHolder.TxtCityCG20111.EnsureVisible();
            Keyboard.Press(CG2011_City);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.MainContentHolder.TxtZipCodeCG2011' at Center.", repo.ApplicationUnderTest.MainContentHolder.TxtZipCodeCG2011Info, new RecordItemIndex(8));
            repo.ApplicationUnderTest.MainContentHolder.TxtZipCodeCG2011.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CG2011_ZipCode' with focus on 'ApplicationUnderTest.MainContentHolder.TxtZipCodeCG2011'.", repo.ApplicationUnderTest.MainContentHolder.TxtZipCodeCG2011Info, new RecordItemIndex(9));
            repo.ApplicationUnderTest.MainContentHolder.TxtZipCodeCG2011.EnsureVisible();
            Keyboard.Press(CG2011_ZipCode);
            Delay.Milliseconds(0);
            
            // Header text
            Report.Log(ReportLevel.Info, "Section", "Header text", new RecordItemIndex(10));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.MainContentHolder.TxtCompanyNameCG2011' at Center.", repo.ApplicationUnderTest.MainContentHolder.TxtCompanyNameCG2011Info, new RecordItemIndex(11));
            repo.ApplicationUnderTest.MainContentHolder.TxtCompanyNameCG2011.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CG2011_CompanyName' with focus on 'ApplicationUnderTest.MainContentHolder.TxtCompanyNameCG2011'.", repo.ApplicationUnderTest.MainContentHolder.TxtCompanyNameCG2011Info, new RecordItemIndex(12));
            repo.ApplicationUnderTest.MainContentHolder.TxtCompanyNameCG2011.PressKeys(CG2011_CompanyName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.MainContentHolder.TxtAddress1CG2011' at Center.", repo.ApplicationUnderTest.MainContentHolder.TxtAddress1CG2011Info, new RecordItemIndex(13));
            repo.ApplicationUnderTest.MainContentHolder.TxtAddress1CG2011.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CG2011_Address1' with focus on 'ApplicationUnderTest.MainContentHolder.TxtAddress1CG2011'.", repo.ApplicationUnderTest.MainContentHolder.TxtAddress1CG2011Info, new RecordItemIndex(14));
            repo.ApplicationUnderTest.MainContentHolder.TxtAddress1CG2011.PressKeys(CG2011_Address1);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.MainContentHolder.TxtAddress2CG2011' at Center.", repo.ApplicationUnderTest.MainContentHolder.TxtAddress2CG2011Info, new RecordItemIndex(15));
            repo.ApplicationUnderTest.MainContentHolder.TxtAddress2CG2011.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CG2011_Address2' with focus on 'ApplicationUnderTest.MainContentHolder.TxtAddress2CG2011'.", repo.ApplicationUnderTest.MainContentHolder.TxtAddress2CG2011Info, new RecordItemIndex(16));
            repo.ApplicationUnderTest.MainContentHolder.TxtAddress2CG2011.EnsureVisible();
            Keyboard.Press(CG2011_Address2);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.MainContentHolder.TxtCityCG20111' at Center.", repo.ApplicationUnderTest.MainContentHolder.TxtCityCG20111Info, new RecordItemIndex(17));
            repo.ApplicationUnderTest.MainContentHolder.TxtCityCG20111.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CG2011_City' with focus on 'ApplicationUnderTest.MainContentHolder.TxtCityCG20111'.", repo.ApplicationUnderTest.MainContentHolder.TxtCityCG20111Info, new RecordItemIndex(18));
            repo.ApplicationUnderTest.MainContentHolder.TxtCityCG20111.EnsureVisible();
            Keyboard.Press(CG2011_City);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.MainContentHolder.TxtZipCodeCG2011' at Center.", repo.ApplicationUnderTest.MainContentHolder.TxtZipCodeCG2011Info, new RecordItemIndex(19));
            repo.ApplicationUnderTest.MainContentHolder.TxtZipCodeCG2011.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CG2011_ZipCode' with focus on 'ApplicationUnderTest.MainContentHolder.TxtZipCodeCG2011'.", repo.ApplicationUnderTest.MainContentHolder.TxtZipCodeCG2011Info, new RecordItemIndex(20));
            repo.ApplicationUnderTest.MainContentHolder.TxtZipCodeCG2011.EnsureVisible();
            Keyboard.Press(CG2011_ZipCode);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
