///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sid_FCGAProject.GL_Product
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The FWCIQuoteDocuments recording.
    /// </summary>
    [TestModule("43373bc6-02f4-4477-92f1-d08ac557e43d", ModuleType.Recording, 1)]
    public partial class FWCIQuoteDocuments : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repository.
        /// </summary>
        public static global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repo = global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository.Instance;

        static FWCIQuoteDocuments instance = new FWCIQuoteDocuments();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public FWCIQuoteDocuments()
        {
            FWCIPremium = "0";
            QuoteDocPath = "Download";
            WorksheetPath = "Download";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static FWCIQuoteDocuments Instance
        {
            get { return instance; }
        }

#region Variables

        string _FWCIPremium;

        /// <summary>
        /// Gets or sets the value of variable FWCIPremium.
        /// </summary>
        [TestVariable("9042cf7f-589a-4e1f-80ae-aecb22435fac")]
        public string FWCIPremium
        {
            get { return _FWCIPremium; }
            set { _FWCIPremium = value; }
        }

        string _QuoteDocPath;

        /// <summary>
        /// Gets or sets the value of variable QuoteDocPath.
        /// </summary>
        [TestVariable("af7908f4-6bf3-40ea-8b34-85fb271d540a")]
        public string QuoteDocPath
        {
            get { return _QuoteDocPath; }
            set { _QuoteDocPath = value; }
        }

        string _WorksheetPath;

        /// <summary>
        /// Gets or sets the value of variable WorksheetPath.
        /// </summary>
        [TestVariable("d4525c30-9e01-462a-8917-61f815659ec8")]
        public string WorksheetPath
        {
            get { return _WorksheetPath; }
            set { _WorksheetPath = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.FwcPremium' at Center.", repo.ApplicationUnderTest.FwcPremiumInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.FwcPremium.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'ApplicationUnderTest.FwcPremium' and assigning its value to variable 'FWCIPremium'.", repo.ApplicationUnderTest.FwcPremiumInfo, new RecordItemIndex(1));
            FWCIPremium = repo.ApplicationUnderTest.FwcPremium.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", FWCIPremium, new RecordItemIndex(2));
            
            // Download FWCI Quote Docs
            Report.Log(ReportLevel.Info, "Section", "Download FWCI Quote Docs", new RecordItemIndex(3));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.BtnDownloadFWCIQuote' at Center.", repo.ApplicationUnderTest.BtnDownloadFWCIQuoteInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.BtnDownloadFWCIQuote.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(5));
            Delay.Duration(5000, false);
            
            //Report.Screenshot(ReportLevel.Info, "User", "Quote Doc captured", repo.Client, false, new RecordItemIndex(6));
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Navigate_Tab' at Center.", repo.Navigate_TabInfo, new RecordItemIndex(7));
            //repo.Navigate_Tab.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'Client' at Center.", repo.ClientInfo, new RecordItemIndex(8));
            //repo.Client.Click(System.Windows.Forms.MouseButtons.Right);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Chrome.SaveAsCtrlPlusS' at Center.", repo.Chrome.SaveAsCtrlPlusSInfo, new RecordItemIndex(9));
            //repo.Chrome.SaveAsCtrlPlusS.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SaveAs.Text1001' at Center.", repo.SaveAs.Text1001Info, new RecordItemIndex(10));
            //repo.SaveAs.Text1001.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$QuoteDocPath' with focus on 'SaveAs.Text1001'.", repo.SaveAs.Text1001Info, new RecordItemIndex(11));
            //repo.SaveAs.Text1001.PressKeys(QuoteDocPath);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SaveAs.ButtonSave' at Center.", repo.SaveAs.ButtonSaveInfo, new RecordItemIndex(12));
            //repo.SaveAs.ButtonSave.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(13));
            //Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'QDCFWCIQ219117110540GLACCEPTED0902.Close' at Center.", repo.QDCFWCIQ219117110540GLACCEPTED0902.CloseInfo, new RecordItemIndex(14));
            repo.QDCFWCIQ219117110540GLACCEPTED0902.Close.Click();
            Delay.Milliseconds(0);
            
            // Download FWCI Worksheet Docs
            Report.Log(ReportLevel.Info, "Section", "Download FWCI Worksheet Docs", new RecordItemIndex(15));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.BtnDownloadFWCIRatingWorksheet' at Center.", repo.ApplicationUnderTest.BtnDownloadFWCIRatingWorksheetInfo, new RecordItemIndex(16));
            repo.ApplicationUnderTest.BtnDownloadFWCIRatingWorksheet.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(17));
            Delay.Duration(5000, false);
            
            //Report.Screenshot(ReportLevel.Info, "User", "worksheet captured", repo.Client, false, new RecordItemIndex(18));
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'Client' at Center.", repo.ClientInfo, new RecordItemIndex(19));
            //repo.Client.Click(System.Windows.Forms.MouseButtons.Right);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Chrome.SaveAsCtrlPlusS' at Center.", repo.Chrome.SaveAsCtrlPlusSInfo, new RecordItemIndex(20));
            //repo.Chrome.SaveAsCtrlPlusS.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SaveAs.Text1001' at Center.", repo.SaveAs.Text1001Info, new RecordItemIndex(21));
            //repo.SaveAs.Text1001.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$WorksheetPath' with focus on 'SaveAs.Text1001'.", repo.SaveAs.Text1001Info, new RecordItemIndex(22));
            //repo.SaveAs.Text1001.PressKeys(WorksheetPath);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SaveAs.ButtonSave' at Center.", repo.SaveAs.ButtonSaveInfo, new RecordItemIndex(23));
            //repo.SaveAs.ButtonSave.Click();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Worksheet.Close1' at Center.", repo.Worksheet.Close1Info, new RecordItemIndex(24));
            repo.Worksheet.Close1.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(25));
            Delay.Duration(2000, false);
            
            // Select Carrier
            Report.Log(ReportLevel.Info, "Section", "Select Carrier", new RecordItemIndex(26));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.BtnCarrierFWCI' at Center.", repo.ApplicationUnderTest.BtnCarrierFWCIInfo, new RecordItemIndex(27));
            repo.ApplicationUnderTest.BtnCarrierFWCI.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
