///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sid_FCGAProject.GL_Product
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The GLReferralQuotePage recording.
    /// </summary>
    [TestModule("3b9d5c81-a95c-4214-9fcd-cc7334c76d8c", ModuleType.Recording, 1)]
    public partial class GLReferralQuotePage : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repository.
        /// </summary>
        public static global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repo = global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository.Instance;

        static GLReferralQuotePage instance = new GLReferralQuotePage();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public GLReferralQuotePage()
        {
            GLReferralComment = "OK";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static GLReferralQuotePage Instance
        {
            get { return instance; }
        }

#region Variables

        string _GLReferralComment;

        /// <summary>
        /// Gets or sets the value of variable GLReferralComment.
        /// </summary>
        [TestVariable("d2f9eb44-c046-49b5-83c6-7a93c5da89c4")]
        public string GLReferralComment
        {
            get { return _GLReferralComment; }
            set { _GLReferralComment = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(0));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TxtRefferal' at Center.", repo.ApplicationUnderTest.TxtRefferalInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.TxtRefferal.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$GLReferralComment' with focus on 'ApplicationUnderTest.TxtRefferal'.", repo.ApplicationUnderTest.TxtRefferalInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.TxtRefferal.PressKeys(GLReferralComment);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.BtnDone' at Center.", repo.ApplicationUnderTest.BtnDoneInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.BtnDone.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(4));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.LnkSignOut' at Center.", repo.ApplicationUnderTest.LnkSignOutInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.LnkSignOut.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(6));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HttpsQawinstonFwcinsComFWCPortalP.Close2' at Center.", repo.HttpsQawinstonFwcinsComFWCPortalP.Close2Info, new RecordItemIndex(7));
            repo.HttpsQawinstonFwcinsComFWCPortalP.Close2.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
