///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sid_FCGAProject
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The UW_SubmitandRerate recording.
    /// </summary>
    [TestModule("b600cd3e-a938-4974-be4b-ed10f89703e3", ModuleType.Recording, 1)]
    public partial class UW_SubmitandRerate : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repository.
        /// </summary>
        public static global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repo = global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository.Instance;

        static UW_SubmitandRerate instance = new UW_SubmitandRerate();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public UW_SubmitandRerate()
        {
            UWStatus = "3";
            UWMessages = "Hello Agent";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static UW_SubmitandRerate Instance
        {
            get { return instance; }
        }

#region Variables

        string _UWStatus;

        /// <summary>
        /// Gets or sets the value of variable UWStatus.
        /// </summary>
        [TestVariable("eaf8c663-c9bd-4237-b66d-d7329a93ee60")]
        public string UWStatus
        {
            get { return _UWStatus; }
            set { _UWStatus = value; }
        }

        string _UWMessages;

        /// <summary>
        /// Gets or sets the value of variable UWMessages.
        /// </summary>
        [TestVariable("31ba3126-7347-448f-9540-2e866815b195")]
        public string UWMessages
        {
            get { return _UWMessages; }
            set { _UWMessages = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(0));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '$UWStatus' on item 'ApplicationUnderTest.DdlCurrentStatus'.", repo.ApplicationUnderTest.DdlCurrentStatusInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.DdlCurrentStatus.Element.SetAttributeValue("TagValue", UWStatus);
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.BtnReRate' at Center.", repo.ApplicationUnderTest.BtnReRateInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.BtnReRate.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 30s.", new RecordItemIndex(3));
            Delay.Duration(30000, false);
            
            Ranorex.AutomationHelpers.UserCodeCollections.WebLibrary.ReportFullPageScreenshot(repo.ApplicationUnderTest.SelfInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CLOSE' at Center.", repo.ApplicationUnderTest.CLOSEInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.CLOSE.Click();
            Delay.Milliseconds(0);
            
            Mouse_Click_UWPolicy_Exit(repo.ApplicationUnderTest.UWPolicy.UWPolicy_ExitInfo);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
